FROM python:3.11

RUN apt update -y
RUN pip install --upgrade pip

RUN python -m pip install numpy
RUN python -m pip install discord.py
RUN python -m pip install python-dotenv

# CMD ["python", "app.py"]